import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter/foundation.dart';

class NotificationService {
  final SupabaseClient _supabase;

  NotificationService({required this._supabase});

  Future<void> initialize() async {
    // Note: requires firebase_options.dart which is generated by flutterfire CLI
    // For this prototype, we'll assume Firebase is initialized in main.dart
    
    // Request permission
    final messaging = FirebaseMessaging.instance;
    final settings = await messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );

    if (settings.authorizationStatus == AuthorizationStatus.authorized) {
      final token = await messaging.getToken();
      if (token != null) {
        await _saveToken(token);
      }
      
      // Listen for token updates
      FirebaseMessaging.instance.onTokenRefresh.listen(_saveToken);
      
      // Handle background messages
      FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
      
      // Handle foreground messages
      FirebaseMessaging.onMessage.listen((RemoteMessage message) {
        // Here we could trigger a local notification or update the UI
        debugPrint('Got a message whilst in the foreground!');
        debugPrint('Message data: ${message.data}');
      });
    }
  }

  Future<void> _saveToken(String token) async {
    final userId = _supabase.auth.currentUser?.id;
    if (userId != null) {
      try {
        await _supabase
            .from('profiles')
            .update({'fcm_token': token})
            .eq('id', userId);
      } catch (e) {
        debugPrint('Error saving FCM token: $e');
      }
    }
  }
}

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  debugPrint("Handling a background message: ${message.messageId}");
}
